### ISSUE TITLE
Mandatory tag LN is not found for the record type SQ

### ISSUE THREAD

**Issue by ripkrizbi** [gramarga/ConPADE#1]
Hi, I'm getting this error when trying to run ConPADe on a sorted bam file which is a result of mapping Illumina reads with Mosaik. I have two bams from two differnt read/reference pairs and one of them is read without a problem while the other gives the 'LN' error. 

I have checked both headers and they appear to be fairly similar, and of course both contain LN tags for each (and all) SQ record. Any hints?

Here is the complete error message:

> Unhandled Exception: System.Exception: Run failure. ---> System.FormatException:
>  Mandatory tag LN is not found for the record type SQ.
>    at Bio.IO.SAM.SAMParser.ParseSamHeader(List`1 headerStrings)
>    at Bio.IO.SAM.SAMParser.ParseSAMHeader(TextReader reader)
>    at Bio.IO.BAM.BAMParser.GetHeader()
>    at ConPADE.ConPADE.RunFile(String bamName)
>    at ConPADE.ConPADE.RunTasks(RangeCollection tasksToRun, Int64 taskCount)
>    at Bio.Util.Distribute.Locally.Distribute(IDistributable distributableObject)
>    at Bio.Util.Distribute.SelfDistributable.Run()
>    at Bio.Util.ArgumentParser.ArgumentCollection.ConstructAndRun[T](Boolean allowRepeats)
>    --- End of inner exception stack trace ---
>    at Bio.Util.ArgumentParser.ArgumentCollection.ConstructAndRun[T](Boolean allowRepeats)
>    at Bio.Util.ArgumentParser.CommandArguments.ConstructAndRun[T](String[] commandArgs, Boolean allowRepeats)
>    at ConPADE.ConPADE.Main(String[] args)

BAM1 header (opens without problems):

> @HD     VN:1.0  SO:coordinate
> @SQ     SN:NODE_1_length_95091_cov_5.37297_ID_1 LN:95091        M5:ba45871d82bf37abf3b85964ddb34457
> @SQ     SN:NODE_2_length_55030_cov_10.6494_ID_3 LN:55030        M5:5b4e2b0dfdf83fa2174a10564aa845be
> @SQ     SN:NODE_3_length_54831_cov_9.14979_ID_5 LN:54831        M5:f26061df0eaba295b5dd970646ec8c14
> @SQ     SN:NODE_4_length_48796_cov_3.85295_ID_7 LN:48796        M5:7dbe69edb12c950a7d5ff5dabc40ee83
> @SQ     SN:NODE_5_length_48059_cov_11.4417_ID_9 LN:48059        M5:c42292ebb05a04e45b51fc398c5b4939
> @SQ     SN:NODE_6_length_39903_cov_11.5485_ID_11        LN:39903        M5:506db950bb97fe683e574ef721a7ab46
> @SQ     SN:NODE_7_length_39205_cov_4.89825_ID_13        LN:39205        M5:df82e1fa81548724f9b1f575eec913b6
> ...

BAM2 header (gives the above error):

> @HD     VN:1.0  SO:coordinate
> @SQ     SN:NODE_1_length_93411_cov_0.144709_ID_1        LN:93411        M5:8b01625bf64bb292a38b99a677351c1d
> @SQ     SN:NODE_2_length_48402_cov_0.0966546_ID_3       LN:48402        M5:50f7d065d94f84bc1bcbaba03b84fe3f
> @SQ     SN:NODE_3_length_48260_cov_0.0478674_ID_5       LN:48260        M5:bc07aeff1158bd8114b03a4518f0c70b
> @SQ     SN:NODE_4_length_44706_cov_0.100406_ID_7        LN:44706        M5:72c2c248c7e956a4d83b7b3080a0f0a0
> @SQ     SN:NODE_5_length_32355_cov_0.047226_ID_9        LN:32355        M5:34eb991970af2a35b78386f9e4dfda07
> @SQ     SN:NODE_6_length_29675_cov_0.0281914_ID_11      LN:29675        M5:326b5e945aa6fc94a9e991b2e763c0fa
> @SQ     SN:NODE_7_length_28543_cov_0.0211852_ID_13      LN:28543        M5:7dacbc49ac0bd3dd0c6179054a3c9636
> @SQ     SN:NODE_8_length_25204_cov_0.416477_ID_15       LN:25204        M5:280500b2e39e63c7768c185f0a39b126
> ...

**Comment by gramarga** [comment]
Dear **ripkrizbi**,

Thank you for your feedback.

We have uploaded a new version which fixes this bug.
Please let us know of any other problems.

I will close this issue.

Best,
Gabriel
