### ISSUE TITLE
Is there a UNIX version of CanPADE ?

### ISSUE THREAD

**Issue by ademcan** [gramarga/ConPADE#2]
Thank you for this tool, it looks really interesting and I would like to give it a try with my own dataset. However, we are running a computer cluster based on UNIX and therefore I cannot run ConPADE as is. Is there any linux version planned or already available?
Thanks

**Comment by gramarga** [comment]
Hello, ademcan.

You can run it as is in a Unix system using mono.
Alternatively, you can compile the source code with Xamarin Studio.

Hope this helps!
