### ISSUE TITLE
"'Properties/AssemblyInfo.cs' could not be found"

### ISSUE THREAD

**Issue by TayteCampbell** [gramarga/ConPADE#3]
I'm attempting to build ConPADE on Xamarin Studio and I linked to the .net bio libraries but I keep getting the following error:

"Source file 'Properties/AssemblyInfo.cs' could not be found"

Any tips on how to fix this problem?

**Comment by gramarga** [comment]
Hello,

Which version of the .NET Framework are you targeting?

Please, will you try version 4.0 and see if this works?

Best,
Gabriel

**Comment by TayteCampbell** [comment]
I updated my .NET framework (I was using version 2.0) but now I'm getting the following error:

"Application Configuration file "app.config" is invalid. Could not find file "

**Comment by gramarga** [comment]
Understood.
I am out of the office for a week, but as soon as possible I will try to reproduce your error and give you more complete details for compilation.

In the meantime, you can use the current binary files on Linux with mono.

**Comment by TayteCampbell** [comment]
I was able to get it to work on Linux with mono. Thanks!
